### PR TITLE
Add ability to import custom CSS files without overwriting templates

### PR DESCRIPTION
**Pull request by jlumbroso**
Made the change suggested by digitalcraftsman:
https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

With this, user can specify arbitrary number of overriding CSS files to be imported in the header, without having to override the header.

### CODE REVIEW

**Comment by goodroot** [comment]
Thanks jlumbroso!!

**Comment by jlumbroso** [comment]
Thanks for the awesome theme!

**Comment by Pac23** [comment]
@goodroot 

`` 
hugo
ERROR: 2018/06/11 22:36:52 template.go:350: template: theme/_default/single.html:7: function "slice" not defined
ERROR: 2018/06/11 22:36:52 general.go:222: Error while rendering taxonomy category: template: theme/_default/list.html:7:3: executing "theme/_default/list.html" at <.Content>: Content is not a field of struct type *hugolib.Node

`
These are the errors i have been getting

**Comment by goodroot** [comment]
@Pac23 Odd! I will have time to look at this early in the week. If you can provide anymore information that might help me debug, it would be appreciated.

**Comment by Pac23** [comment]
so what i first did was followed the method mentioned in the repo's readme then started the server,the site only renders the main top bar,every link in it is clickable but rest of the site wont render. 

I even tried cloning your already live site repo and doing it but results in the same problem.

https://imgur.com/a/tfc2flb i hope this screenshot helps

**Pull request merged**
